server:
  port: 8080
  context-path: /ecc

spring:
  profiles:
    active: prd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.zjdex.core.costom.CustomMysqlDialect

