spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fwdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

sjt:
  url: http://apidatatest.datatang.com/data/credit/
  apikey: c8d7ac55b22faa229a7fb9243b017f31
